### ISSUE TITLE
error ketika mengikuti instruksi di README.md

### ISSUE THREAD

**Issue by mohamad-supangat** [bandithijo/st-bandithijo#1]
mungkin sebaiknya binary jangan di sertakan pada repo biarkan system sendiri sendiri untuk mencompilenya mas, karna saya menemukan error di system saya 

[![asciicast](https://asciinema.org/a/5d9JOIpCGVG42cLGdVNOeKHxU.svg)](https://asciinema.org/a/5d9JOIpCGVG42cLGdVNOeKHxU)

**Comment by bandithijo** [comment]
oh siap.
Nice catch!
Terima kasih yaa masukannya.
Nanti saya make clean.

**Comment by bandithijo** [comment]
@mohamad-supangat 
Sip! Sudah tak clean yaa di commit ini a1abbaa

**Comment by mohamad-supangat** [comment]
Mantep mas, ditunggu patch selanjutnya
